spring.application.name=carregaja

spring.datasource.url=jdbc:mysql://localhost:3306/carregaja
spring.datasource.username=root
spring.datasource.password=${MYSQL_SENHA}

spring.jpa.hibernate.ddl-auto=update
